services:
  db:
    image: postgres:16-alpine
    container_name: events_db
    environment:
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: events_pass
      POSTGRES_DB: eventsdb
    ports:
      - "5432:5432"